fail_fast: false
repos:
-   hooks:
    -   args:
        - --fix
        id: ruff
    -   id: ruff-format
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.7
-   hooks:
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: no-commit-to-branch
    -   id: trailing-whitespace
    -   args:
        - --autofix
        - --indent=4
        id: pretty-format-json
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
-   hooks:
    -   args:
        - --in-place
        - --config
        - ./pyproject.toml
        id: docformatter
    repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
-   hooks:
    -   id: fmt
    -   id: cargo-check
    -   id: clippy
    -   id: build
    -   id: test
    repo: https://github.com/FeryET/pre-commit-rust
    rev: v1.1.1
-   hooks:
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
    -   id: check-json
    -   id: check-xml
    -   id: check-toml
    -   id: no-commit-to-branch
    -   args:
        - --autofix
        - --indent=4
        id: pretty-format-json
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
